404s with formats other than html
psu-libraries/myaccount pull request #320
Opened 2020-11-10 21:10 UTC by banukutlu

#294

2020-11-11 13:40 UTC, cdmo commented
I'm still getting a `500` when I try to go to http://localhost:3001/wcd/system.xml.

2020-11-11 13:43 UTC, cdmo requested changes
Needs to be that unauthenticated traffic going to http://localhost:3001/wcd/system.xml should experience a 404 or perhaps better would be a 401 Unauthenticated

2020-11-11 14:06 UTC, banukutlu commented
> Needs to be that unauthenticated traffic going to http://localhost:3001/wcd/system.xml should experience a 404 or perhaps better would be a 401 Unauthenticated

Could you share a screenshot or logs? When going there I am seeing the 404 page 🤔

2020-11-11 14:09 UTC, banukutlu commented
> Needs to be that unauthenticated traffic going to http://localhost:3001/wcd/system.xml should experience a 404 or perhaps better would be a 401 Unauthenticated

looking into it 👍  I missed to check unauthenticated requests

2020-11-12 14:33 UTC, cdmo requested changes
When unauthenticated, I go to http://localhost:3001/wcd/system.xml and I am getting an error `undefined method `[]' for nil:NilClass` see [Screen Shot 2020-11-12 at 9 29 08 AM](https://user-images.githubusercontent.com/523381/98952843-edb4af00-24c9-11eb-898f-50ff199d231d.png)

Also, I am unable to login into the application. 

🤔

2020-11-13 18:56 UTC, banukutlu commented
> When unauthenticated, I go to http://localhost:3001/wcd/system.xml and I am getting an error `undefined method `[]' for nil:NilClass` see [Screen Shot 2020-11-12 at 9 29 08 AM](https://user-images.githubusercontent.com/523381/98952843-edb4af00-24c9-11eb-898f-50ff199d231d.png)
> 
> Also, I am unable to login into the application.
> 
> 🤔

made some changes, rebased from master to get that patron validation to use that to fix this issue, it seems to be working on my local, could you give it a try again?

2020-11-16 16:53 UTC, cdmo commented on app/controllers/errors_controller.rb
> +      format.all { render status: 404, formats: :html, content_type: 'text/html' }
```suggestion
      format.any { render status: 404, formats: :html, content_type: 'text/html' }
```

"Respond to also allows you to specify a common block for different formats by using any:" [respond_to](https://apidock.com/rails/ActionController/MimeResponds/respond_to)

this seems to work, did you try it before and it didn't?

2020-11-16 23:49 UTC, cdmo requested changes
We are considering forcing authentication on the `ErrorsController` which essentially completely seals off the application to public traffic.

2020-11-18 18:02 UTC, cdmo approved these changes
LGTM! 🎸

2020-11-18 18:04 UTC, merged