updated matomo script
psu-libraries/myaccount pull request #642
Opened 2023-06-15 13:44 UTC by Smullz622

Fixes #639 

Turns out the Matomo script was already there, but the id_site was pointing to stage. This should point it to prod.

2023-06-15 14:16 UTC, whereismyjetpack requested changes

2023-06-15 14:16 UTC, whereismyjetpack commented on app/views/layouts/_head.html.erb
> +      _paq.push(['setSiteId', '13']);
we shouldn't hardcode the site_id here. I think we were doing it right before, with `Settings.matomo_id` I think we just need to update the matomo_id in the prod deployment to be 11.

2023-06-15 16:32 UTC, whereismyjetpack commented
I've created a non-production myaccount website in matomo, it's site_id is 38. You can add this into settings, and then in prod we have overridden in to be 14

2023-06-15 16:50 UTC, Smullz622 commented
> I've created a non-production myaccount website in matomo, it's site_id is 38. You can add this into settings, and then in prod we have overridden in to be 14

Should the override be in `config/settings/production.yml` or in the helm chart?

2023-06-15 17:57 UTC, whereismyjetpack commented on config/settings.yml
> +matomo_id: 13
@Smullz622 I would change this to be 38, and we'll leave the override in the config-repo!

2023-06-16 13:37 UTC, whereismyjetpack approved these changes

2023-06-16 13:41 UTC, merged